function __DeprocatedFunctions() {
	static __struct = {
	"achievement_available": achievement_available,
	"achievement_get_challenges": achievement_get_challenges,
	"achievement_get_pic": achievement_get_pic,
	"achievement_increment": achievement_increment,
	"achievement_load_friends": achievement_load_friends,
	"achievement_load_leaderboard": achievement_load_leaderboard,
	"achievement_load_progress": achievement_load_progress,
	"achievement_login": achievement_login,
	"achievement_login_status": achievement_login_status,
	"achievement_logout": achievement_logout,
	"achievement_post": achievement_post,
	"achievement_post_score": achievement_post_score,
	"achievement_reset": achievement_reset,
	"achievement_send_challenge": achievement_send_challenge,
	"achievement_show_achievements": achievement_show_achievements,
	"achievement_show_challenge_notifications": achievement_show_challenge_notifications,
	"achievement_show_leaderboards": achievement_show_leaderboards,
	"cloud_file_save": cloud_file_save,
	"cloud_string_save": cloud_string_save,
	"cloud_synchronise": cloud_synchronise,
	"push_cancel_local_notification": push_cancel_local_notification,
	"push_get_first_local_notification": push_get_first_local_notification,
	"push_get_next_local_notification": push_get_next_local_notification,
	"push_local_notification": push_local_notification,
	"get_integer": get_integer,
	"get_string": get_string,
	"analytics_event": analytics_event,
	"analytics_event_ext": analytics_event_ext,
	"array_length_1d": array_length_1d,
	"array_length_2d": array_length_2d,
	"array_height_2d": array_height_2d,
	"audio_resume_music": audio_resume_music,
	"audio_music_is_playing": audio_music_is_playing,
	"audio_pause_music": audio_pause_music,
	"audio_play_music": audio_play_music,
	"audio_stop_music": audio_stop_music,
	"audio_music_gain": audio_music_gain,
	"audio_system": audio_system,
	"room_set_background_colour": room_set_background_colour,
	"room_set_background_color": room_set_background_color,
	"achievement_event": achievement_event,
	"achievement_show": achievement_show,
	"achievement_get_info": achievement_get_info,
//	"ads_enable": ads_enable,
//	"ads_disable": ads_disable,
//	"ads_setup": ads_setup,
//	"ads_engagement_launch": ads_engagement_launch,
//	"ads_engagement_available": ads_engagement_available,
//	"ads_engagement_active": ads_engagement_active,
//	"ads_event": ads_event,
//	"ads_event_preload": ads_event_preload,
//	"ads_set_reward_callback": ads_set_reward_callback,
//	"ads_get_display_height": ads_get_display_height,
//	"ads_get_display_width": ads_get_display_width,
//	"ads_move": ads_move,
//	"ads_interstitial_available": ads_interstitial_available,
//	"ads_interstitial_display": ads_interstitial_display,
	"iap_activate": iap_activate,
	"iap_status": iap_status,
	"iap_enumerate_products": iap_enumerate_products,
	"iap_restore_all": iap_restore_all,
	"iap_acquire": iap_acquire,
	"iap_consume": iap_consume,
	"iap_product_details": iap_product_details,
	"iap_purchase_details": iap_purchase_details,
	"win8_livetile_tile_notification": win8_livetile_tile_notification,
	"win8_livetile_tile_clear": win8_livetile_tile_clear,
	"win8_livetile_badge_notification": win8_livetile_badge_notification,
	"win8_livetile_badge_clear": win8_livetile_badge_clear,
	"win8_livetile_queue_enable": win8_livetile_queue_enable,
	"win8_secondarytile_pin": win8_secondarytile_pin,
	"win8_secondarytile_badge_notification": win8_secondarytile_badge_notification,
	"win8_secondarytile_delete": win8_secondarytile_delete,
	"win8_livetile_notification_begin": win8_livetile_notification_begin,
	"win8_livetile_notification_secondary_begin": win8_livetile_notification_secondary_begin,
	"win8_livetile_notification_expiry": win8_livetile_notification_expiry,
	"win8_livetile_notification_tag": win8_livetile_notification_tag,
	"win8_livetile_notification_text_add": win8_livetile_notification_text_add,
	"win8_livetile_notification_image_add": win8_livetile_notification_image_add,
	"win8_livetile_notification_end": win8_livetile_notification_end,
	"win8_appbar_enable": win8_appbar_enable,
	"win8_appbar_add_element": win8_appbar_add_element,
	"win8_appbar_remove_element": win8_appbar_remove_element,
	"win8_settingscharm_add_entry": win8_settingscharm_add_entry,
	"win8_settingscharm_add_html_entry": win8_settingscharm_add_html_entry,
	"win8_settingscharm_add_xaml_entry": win8_settingscharm_add_xaml_entry,
	"win8_settingscharm_set_xaml_property": win8_settingscharm_set_xaml_property,
	"win8_settingscharm_get_xaml_property": win8_settingscharm_get_xaml_property,
	"win8_settingscharm_remove_entry": win8_settingscharm_remove_entry,
	"win8_share_image": win8_share_image,
	"win8_share_screenshot": win8_share_screenshot,
	"win8_share_file": win8_share_file,
	"win8_share_url": win8_share_url,
	"win8_share_text": win8_share_text,
	"win8_search_enable": win8_search_enable,
	"win8_search_disable": win8_search_disable,
	"win8_search_add_suggestions": win8_search_add_suggestions,
	"win8_device_touchscreen_available": win8_device_touchscreen_available,
	"win8_license_initialize_sandbox": win8_license_initialize_sandbox,
	"win8_license_trial_version": win8_license_trial_version,
	"uwp_livetile_tile_clear": uwp_livetile_tile_clear,
	"uwp_livetile_badge_notification": uwp_livetile_badge_notification,
	"uwp_livetile_badge_clear": uwp_livetile_badge_clear,
	"uwp_livetile_queue_enable": uwp_livetile_queue_enable,
	"uwp_secondarytile_pin": uwp_secondarytile_pin,
	"uwp_secondarytile_badge_notification": uwp_secondarytile_badge_notification,
	"uwp_secondarytile_delete": uwp_secondarytile_delete,
	"uwp_secondarytile_badge_clear": uwp_secondarytile_badge_clear,
	"uwp_secondarytile_tile_clear": uwp_secondarytile_tile_clear,
	"uwp_livetile_notification_begin": uwp_livetile_notification_begin,
	"uwp_livetile_notification_secondary_begin": uwp_livetile_notification_secondary_begin,
	"uwp_livetile_notification_expiry": uwp_livetile_notification_expiry,
	"uwp_livetile_notification_tag": uwp_livetile_notification_tag,
	"uwp_livetile_notification_text_add": uwp_livetile_notification_text_add,
	"uwp_livetile_notification_image_add": uwp_livetile_notification_image_add,
	"uwp_livetile_notification_end": uwp_livetile_notification_end,
	"uwp_appbar_enable": uwp_appbar_enable,
	"uwp_appbar_add_element": uwp_appbar_add_element,
	"uwp_appbar_remove_element": uwp_appbar_remove_element,
	"uwp_device_touchscreen_available": uwp_device_touchscreen_available,
	"winphone_license_trial_version": winphone_license_trial_version,
	"winphone_tile_title": winphone_tile_title,
	"winphone_tile_count": winphone_tile_count,
	"winphone_tile_back_title": winphone_tile_back_title,
	"winphone_tile_back_content": winphone_tile_back_content,
	"winphone_tile_back_content_wide": winphone_tile_back_content_wide,
	"winphone_tile_front_image": winphone_tile_front_image,
	"winphone_tile_front_image_small": winphone_tile_front_image_small,
	"winphone_tile_front_image_wide": winphone_tile_front_image_wide,
	"winphone_tile_back_image": winphone_tile_back_image,
	"winphone_tile_back_image_wide": winphone_tile_back_image_wide,
	"winphone_tile_background_colour": winphone_tile_background_colour,
	"winphone_tile_background_color": winphone_tile_background_color,
	"winphone_tile_icon_image": winphone_tile_icon_image,
	"winphone_tile_small_icon_image": winphone_tile_small_icon_image,
	"winphone_tile_wide_content": winphone_tile_wide_content,
	"winphone_tile_cycle_images": winphone_tile_cycle_images,
	"winphone_tile_small_background_image": winphone_tile_small_background_image,
	"vertex_format_add_textcoord": vertex_format_add_textcoord,
	"push_get_application_badge_number": push_get_application_badge_number,
	"push_set_application_badge_number": push_set_application_badge_number,
	"layer_tile_exists": layer_tile_exists,
	"layer_tile_create": layer_tile_create,
	"layer_tile_destroy": layer_tile_destroy,
	"layer_tile_change": layer_tile_change,
	"layer_tile_xscale": layer_tile_xscale,
	"layer_tile_yscale": layer_tile_yscale,
	"layer_tile_blend": layer_tile_blend,
	"layer_tile_alpha": layer_tile_alpha,
	"layer_tile_x": layer_tile_x,
	"layer_tile_y": layer_tile_y,
	"layer_tile_region": layer_tile_region,
	"layer_tile_visible": layer_tile_visible,
	"layer_tile_get_sprite": layer_tile_get_sprite,
	"layer_tile_get_xscale": layer_tile_get_xscale,
	"layer_tile_get_yscale": layer_tile_get_yscale,
	"layer_tile_get_blend": layer_tile_get_blend,
	"layer_tile_get_alpha": layer_tile_get_alpha,
	"layer_tile_get_x": layer_tile_get_x,
	"layer_tile_get_y": layer_tile_get_y,
	"layer_tile_get_region": layer_tile_get_region,
	"layer_tile_get_visible": layer_tile_get_visible,
}
return __struct;
}
