#define osg
///GAME SCRIPT

////////// INITIALIZE //////////

//resize game
if (!ds_exists(0, ds_type_priority)) {
    //room_width = 800;
    //room_height = 608;
    //window_set_size(room_width, room_height);
    texture_set_interpolation(false);
    //application_surface_enable(false);
    room_speed = 60;
    ds_priority_create();
    exit;
}
                                                                                                   ////////// HEADING //////////
if (!ds_exists(0, ds_type_map)) {                                                                   //===== SUBHEADING =====
                                                                                                          //== Title ==        
    //===== INIT VARS =====                                                                                 //category
    randomize();
    
    //temporary tutorial
    show_message(
    @"~~~~~~ Welcome to shadowspear1's ~~~~~~
     ~~~ ONE SCRIPT - TOWER DEFENSE GAME ~~~
    
    I didn't have time to make a tutorial, so here's a run-through. 
    
    Use the menu at the bottom of the screen to buy towers.
    
    You can place them on any open tile, besides on the path.
    
    THE FOLLOWING WERE NOT IMPLEMENTED: 
    You can click on a placed tower to view it's stats, or upgrade it if you wish.
    
    It plays like your average tower defense, so keep killing the creeps 
    and try to last as long as possible! Good luck."
    );
    
    ds_map_create();
    ds_map_add(0, "count", 0);
    ds_map_add(0, "money", 950);
    ds_map_add(0, "hp", 200);
    ds_map_add(0, "debug", false);
    
    var tile_grid = ds_grid_create(25, 19); //grid that allows each maptile to hold a specific value
    ds_map_add(0, "tile_grid", tile_grid);
    
    ds_map_add(0, "xpos", 100);
    ds_map_add(0, "ypos", 100);
    ds_map_add(0, "xvel", 0);
    ds_map_add(0, "yvel", 0);
    
    ds_map_add(0, "on_title", true);        //are we on title screen?
    
    ds_map_add(0, "menu_open", false);      //is menu open?
    ds_map_add(0, "menu_count", 0);         //count variable for open animation
    //ds_map_add(0, "menu_locked", false);    //should menu stay open?
    ds_map_add(0, "menu_tower_held", -1);   //what is the id of the tower we are placing? (-1 means no tower beign placed)
    ds_map_add(0, "need_money_count", -1);  //count variable for "not enough money" display on screen
    
    var tower_id_info = ds_grid_create(485+10+1, 3)  //grid for storing tower data based on their TOWER GRID ID (10 + grid_position)
    ds_map_add(0, "tower_id_info", tower_id_info);  //[10, 0...1...2] => tower_type; tower_upgr_lvl; tower_att_count
    
    var towers = ds_grid_create(2, 3);      //grid containing basic tower info for menu: name, description, cost
    ds_map_add(0, "towers", towers);
    towers[# 0, 0] = "Arrow Tower";
    towers[# 0, 1] = "Weak tower. Shoots accurate arrows";
    towers[# 0, 2] = 250;
    towers[# 1, 0] = "Gun Tower";
    towers[# 1, 1] = "Average tower. Rapidly fires innacurate bullets";
    towers[# 1, 2] = 400;
    
    var tower_arrow = ds_grid_create(5, 5); //stats for each upgr level
    ds_map_add(0, "tower_arrow", tower_arrow);
    //       upgr_cost,                 sell_price,                      dmg,                      att_rate,                     range
    tower_arrow[# 0, 0] = 100;   tower_arrow[# 1, 0] = 150;   tower_arrow[# 2, 0] = 5;   tower_arrow[# 3, 0] = 60;   tower_arrow[# 4, 0] = 350;
    tower_arrow[# 0, 1] = 200;   tower_arrow[# 1, 1] = 200;   tower_arrow[# 2, 1] = 7;   tower_arrow[# 3, 1] = 55;   tower_arrow[# 4, 1] = 380;
    tower_arrow[# 0, 2] = 400;   tower_arrow[# 1, 2] = 300;   tower_arrow[# 2, 2] = 10;   tower_arrow[# 3, 2] = 50;   tower_arrow[# 4, 2] = 410;
    tower_arrow[# 0, 3] = 750;   tower_arrow[# 1, 3] = 500;   tower_arrow[# 2, 3] = 13;   tower_arrow[# 3, 3] = 45;   tower_arrow[# 4, 3] = 440;
    tower_arrow[# 0, 4] =  -1;   tower_arrow[# 1, 4] = 800;   tower_arrow[# 2, 4] = 20;   tower_arrow[# 3, 4] = 40;   tower_arrow[# 4, 4] = 470;
    
    var tower_gun = ds_grid_create(5, 5); //stats for each upgr level
    ds_map_add(0, "tower_gun", tower_gun);
    //      upgr_cost,                sell_price,                  dmg,                   att_rate,                   range
    tower_gun[# 0, 0] = 200;   tower_gun[# 1, 0] = 200;   tower_gun[# 2, 0] = 4;   tower_gun[# 3, 0] = 35;   tower_gun[# 4, 0] = 200;
    tower_gun[# 0, 1] = 300;   tower_gun[# 1, 1] = 300;   tower_gun[# 2, 1] = 6;   tower_gun[# 3, 1] = 30;   tower_gun[# 4, 1] = 225;
    tower_gun[# 0, 2] = 400;   tower_gun[# 1, 2] = 450;   tower_gun[# 2, 2] = 8;   tower_gun[# 3, 2] = 25;   tower_gun[# 4, 2] = 250;
    tower_gun[# 0, 3] = 500;   tower_gun[# 1, 3] = 650;   tower_gun[# 2, 3] = 10;   tower_gun[# 3, 3] = 20;   tower_gun[# 4, 3] = 275;
    tower_gun[# 0, 4] =  -1;   tower_gun[# 1, 4] = 900;   tower_gun[# 2, 4] = 12;   tower_gun[# 3, 4] = 15;   tower_gun[# 4, 4] = 300;
    
    
    
    
    //===== CREATE SPRITES =====
    
        //== Buffer Sprite Setup ==
        /*
            //generate encoded string from sprite
            var surf_buffer = surface_create(78, 18);
            surface_set_target(surf_buffer);
            draw_sprite(sprite5, 0, 0, 0);
            surface_reset_target();
            var buffer_sprite = buffer_create(78*18*4, buffer_grow, 1);
            buffer_get_surface(buffer_sprite, surf_buffer, 0, 0, 0);  
            var sprite_buffer_64 = buffer_base64_encode(buffer_sprite, 0, buffer_get_size(buffer_sprite));
            clipboard_set_text(string(sprite_buffer_64));
            show_message("Encoded data copied to clipboard.##" + sprite_buffer_64);    
        */
        /*
            //TEMPLATE ~ create sprite from encoded string
            var buffer_sprite = buffer_create(4096, buffer_grow, 1);
            buffer_sprite = buffer_base64_decode("RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/RAAA/0QAAP9EAAD/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/Qv8t/0QAAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9C/y3/RAAA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/0L/Lf9EAAD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/Qv8t/0QAAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9C/y3/RAAA/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/0L/Lf9EAAD/cr25/1mm0v9ZptL/WabS/1mm0v9yvbn/tPh4//anWv9yvbn/WabS/1mm0v9ZptL/WabS/3K9uf+0+Hj/9qda/3K9uf9ZptL/WabS/1mm0v9ZptL/cr25/7T4eP/2p1r/cr25/1mm0v9ZptL/WabS/1mm0v9yvbn/Qv8t/0QAAP+0bBn/m1UA/5tVAP+bVQD/m1UA/7RsGf/2p1r/9qda/7RsGf+bVQD/m1UA/5tVAP+bVQD/tGwZ//anWv/2p1r/tGwZ/5tVAP+bVQD/m1UA/5tVAP+0bBn/9qda//anWv+0bBn/m1UA/5tVAP+bVQD/m1UA/7RsGf9EAAD/RAAA/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/0L/Lf9EAAD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/Qv8t/0QAAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9C/y3/RAAA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/0L/Lf9EAAD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/Qv8t/0QAAP+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9C/y3/RAAA/3K9uf9ZptL/WabS/1mm0v9ZptL/cr25/7T4eP/2p1r/cr25/1mm0v9ZptL/WabS/1mm0v9yvbn/tPh4//anWv9yvbn/WabS/1mm0v9ZptL/WabS/3K9uf+0+Hj/9qda/3K9uf9ZptL/WabS/1mm0v9ZptL/cr25/0L/Lf9EAAD/tGwZ/5tVAP+bVQD/m1UA/5tVAP+0bBn/9qda//anWv+0bBn/m1UA/5tVAP+bVQD/m1UA/7RsGf/2p1r/9qda/7RsGf+bVQD/m1UA/5tVAP+bVQD/tGwZ//anWv/2p1r/tGwZ/5tVAP+bVQD/m1UA/5tVAP+0bBn/RAAA/0QAAP+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9C/y3/RAAA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/0L/Lf9EAAD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/Qv8t/0QAAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9C/y3/RAAA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/0L/Lf9EAAD/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/Qv8t/0QAAP9yvbn/WabS/1mm0v9ZptL/WabS/3K9uf+0+Hj/9qda/3K9uf9ZptL/WabS/1mm0v9ZptL/cr25/7T4eP/2p1r/cr25/1mm0v9ZptL/WabS/1mm0v9yvbn/tPh4//anWv9yvbn/WabS/1mm0v9ZptL/WabS/3K9uf9C/y3/RAAA/7RsGf+bVQD/m1UA/5tVAP+bVQD/tGwZ//anWv/2p1r/tGwZ/5tVAP+bVQD/m1UA/5tVAP+0bBn/9qda//anWv+0bBn/m1UA/5tVAP+bVQD/m1UA/7RsGf/2p1r/9qda/7RsGf+bVQD/m1UA/5tVAP+bVQD/tGwZ/0QAAP9EAAD/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/Qv8t/0QAAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9C/y3/RAAA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/0L/Lf9EAAD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/WabS/5tVAP9ZptL/cr25/7T4eP+0+Hj/cr25/1mm0v9ZptL/m1UA/1mm0v9yvbn/tPh4/7T4eP9yvbn/WabS/1mm0v+bVQD/WabS/3K9uf+0+Hj/tPh4/3K9uf9ZptL/Qv8t/0QAAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9ZptL/m1UA/3K9uf+0+Hj/cr25/3K9uf+0+Hj/cr25/1mm0v+bVQD/cr25/7T4eP9yvbn/cr25/7T4eP9yvbn/WabS/5tVAP9yvbn/tPh4/3K9uf9yvbn/tPh4/3K9uf9C/y3/RAAA/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/3K9uf+0bBn/tPh4/3K9uf9ZptL/WabS/3K9uf+0+Hj/cr25/7RsGf+0+Hj/cr25/1mm0v9ZptL/cr25/7T4eP9yvbn/tGwZ/7T4eP9yvbn/WabS/1mm0v9yvbn/tPh4/0L/Lf9EAAD/Qv8t/0L/Lf9C/y3/Qv8t/0L/Lf9C/y3/Qv8t/0QAAP9C/y3/Qv8t/0L/Lf9C/y3/Qv8t/0L/Lf9C/y3/RAAA/0L/Lf9C/y3/Qv8t/0L/Lf9C/y3/Qv8t/0L/Lf9EAAD/Qv8t/0L/Lf9C/y3/Qv8t/0L/Lf9C/y3/Qv8t/w==");
            var surf_buffer = surface_create(32, 32);
            buffer_set_surface(buffer_sprite, surf_buffer, 0, 0, 0);    //copy the decoded sprite data onto the surface
            var spr_buffer = sprite_create_from_surface(surf_buffer, 0, 0, 32, 32, false, false, 0, 0); //create sprite from this surface
            ds_map_add(0, "spr_buffer", spr_buffer);
            surface_reset_target();
            buffer_delete(buffer_sprite);
            surface_free(surf_buffer);
        */
    
    //== Font Sprite ==
    var buffer_sprite = buffer_create(78*18*4, buffer_wrap, 1);
    buffer_sprite = buffer_base64_decode("AAAAAP//////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA//////////8AAAAA//////////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAP////8AAAAA/////////////////////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAD//////////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA//////////////////////////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////////////////////wAAAAAAAAAA//////////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAD/////AAAAAP////8AAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA//////////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAD/////AAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAD//////////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////wAAAAD/////AAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAD//////////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA//////////8AAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA//////////////////////////8AAAAAAAAAAP////8AAAAA/////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAP////8AAAAA/////wAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAD//////////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////////////////////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////8AAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/////////////////////wAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    var surf_buffer = surface_create(78, 18);
    buffer_set_surface(buffer_sprite, surf_buffer, 0, 0, 0);    //copy the decoded sprite data onto the surface
    var spr_font = sprite_create_from_surface(surf_buffer, 0, 0, 6, 6, false, false, 0, 0);
    for (var j=0; j<3; j++) {
        for (var i=0; i<13; i++) {
            if (i==0 && j==0) { continue; } //skip first char, as we already used it to create the sprite
            sprite_add_from_surface(spr_font, surf_buffer, 6*i, 6*j, 6, 6, false, false);  //create individual sprite for each character from the font
        }
    }
    for (var j=0; j<2; j++) {   //also need to create capital letters, so add all letters to the sprite one more time
        for (var i=0; i<13; i++) {
            sprite_add_from_surface(spr_font, surf_buffer, 6*i, 6*j, 6, 6, false, false);
        }
    }
    ds_map_add(0, "spr_font", spr_font);
    surface_reset_target();
    surface_free(surf_buffer);
    buffer_delete(buffer_sprite);
    
    var fnt_default = font_add_sprite_ext(spr_font, "abcdefghijklmnopqrstuvwxyz0123456789.!:ABCDEFGHIJKLMNOPQRSTUVWXYZ", false, 0);
    ds_map_add(0, "fnt_default", fnt_default);
    draw_set_font(fnt_default);
    
    //== 32px Sprites ==
    var buffer_sprite = buffer_create(4096, buffer_wrap, 1);
    
    //enemy1
    buffer_sprite = buffer_base64_decode("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAef0L/Kq9b/x5/Qv8qr1v/Hn9C/yqvW/8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/x5/Qv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5/Qv8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/yqvW/8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHn9C/yqvW/8ef0L/Kq9b/yqvW/8qr1v/Kq9b/yqvW/8qr1v/Kq9b/x5/Qv8ef0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAef0L/Hn9C/yqvW/8qr1v/Kq9b/yqvW/8qr1v/Kq9b/yqvW/8ef0L/Kq9b/x5/Qv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5/Qv8qr1v/Hn9C/yqvW/8qr1v/Kq9b/yqvW/8qr1v/Kq9b/yqvW/8ef0L/Hn9C/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHn9C/x5/Qv8qr1v/Kq9b/yqvW/8qr1v/Kq9b/yqvW/8qr1v/Hn9C/yqvW/8ef0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAef0L/Kq9b/x5/Qv8qr1v/Hn9C/yqvW/8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/x5/Qv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5/Qv8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/yqvW/8ef0L/Kq9b/x5/Qv8qr1v/Hn9C/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/Hn9C/x5/Qv8ef0L/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUVCv/FFQr/xRUK/8UVCv/FFQr/xRUK/8UVCv/FFQr/xRUK/8UVCv/FFQr/xRUK/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRUK/8UVCv/FFQr/xRUK/8UVCv/FFQr/xRUK/8UVCv/FFQr/xRUK/8UVCv/FFQr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
    var surf_buffer = surface_create(32, 32);
    buffer_set_surface(buffer_sprite, surf_buffer, 0, 0, 0);    //copy the decoded sprite data onto the surface
    var spr_enemy1 = sprite_create_from_surface(surf_buffer, 0, 0, 32, 32, false, false, 0, 0); //create sprite from this surface
    ds_map_add(0, "spr_enemy1", spr_enemy1);
    surface_reset_target();
    surface_free(surf_buffer);
    
    //tower_arrow
    buffer_sprite = buffer_base64_decode("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8mer//Jnq//yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yZ6v/8mer//Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yZ6v/8mer//Jnq//yqH0/8qh9P/KofT/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8qh9P/KofT/yqH0/8mer//Jnq//yZ6v/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/JHW3/y+Z7/8vme//KofT/y+Z7/8qh9P/KofT/yqH0/8qh9P/JHW3/yR1t/8kdbf/KofT/yqH0/8qh9P/KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/KofT/yR1t/8kdbf/JHW3/y+Z7/8qh9P/L5nv/y+Z7/8qh9P/L5nv/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/JHW3/yqH0/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8kdbf/JHW3/yR1t/8qh9P/L5nv/yqH0/8vme//L5nv/yqH0/8vme//KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/JHW3/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/yqH0/8kdbf/JHW3/yqH0/8vme//KofT/y+Z7/8vme//KofT/y+Z7/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/JHW3/yR1t/8qh9P/KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/L5nv/yR1t/8kdbf/KofT/y+Z7/8qh9P/L5nv/y+Z7/8qh9P/L5nv/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8kdbf/JHW3/y+Z7/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8vme//JHW3/yR1t/8qh9P/L5nv/yqH0/8vme//L5nv/yqH0/8vme//KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/L5nv/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/y+Z7/8kdbf/JHW3/yqH0/8vme//KofT/y+Z7/8vme//KofT/y+Z7/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/JHW3/yR1t/8vme//KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/L5nv/yR1t/8kdbf/KofT/y+Z7/8qh9P/L5nv/y+Z7/8qh9P/L5nv/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8kdbf/JHW3/y+Z7/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8vme//JHW3/yR1t/8qh9P/L5nv/yqH0/8vme//L5nv/yqH0/8vme//KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/L5nv/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/y+Z7/8kdbf/JHW3/yqH0/8vme//KofT/y+Z7/8vme//KofT/y+Z7/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/JHW3/yR1t/8vme//KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/L5nv/yR1t/8kdbf/KofT/y+Z7/8qh9P/L5nv/y+Z7/8qh9P/L5nv/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8kdbf/JHW3/y+Z7/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8vme//JHW3/yR1t/8qh9P/L5nv/yqH0/8vme//JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/KofT/yqH0/8qh9P/KofT/yR1t/8kdbf/L5nv/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/y+Z7/8kdbf/JHW3/yqH0/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8qh9P/JHW3/yR1t/8vme//KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/L5nv/yR1t/8kdbf/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8kdbf/JHW3/y+Z7/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8qh9P/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/KofT/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/JHW3/yR1t/8kdbf/KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/JHW3/yR1t/8kdbf/L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8kdbf/JHW3/yR1t/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8kdbf/JHW3/y+Z7/8vme//KofT/yqH0/8qh9P/L5nv/yqH0/8vme//L5nv/y+Z7/8qh9P/L5nv/yqH0/8qh9P/L5nv/yqH0/8kdbf/JHW3/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//KofT/yR1t/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8vme//L5nv/y+Z7/8kdbf/KofT/yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8qh9P/JHW3/y+Z7/8qh9P/KofT/y+Z7/8vme//KofT/yqH0/8vme//KofT/y+Z7/8qh9P/KofT/y+Z7/8qh9P/L5nv/yqH0/8qh9P/L5nv/yR1t/8qh9P/Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJnq//yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8qh9P/KofT/yqH0/8mer//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//yZ6v/8mer//Jnq//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
    var surf_buffer = surface_create(32, 32);
    buffer_set_surface(buffer_sprite, surf_buffer, 0, 0, 0);    //copy the decoded sprite data onto the surface
    var spr_tower_arrow = sprite_create_from_surface(surf_buffer, 0, 0, 32, 32, false, false, 0, 0); //create sprite from this surface
    ds_map_add(0, "spr_tower_arrow", spr_tower_arrow);
    surface_reset_target();
    surface_free(surf_buffer);
    
    //tower_gun
    buffer_sprite = buffer_base64_decode("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApZub/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApZub/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzs7/6Wbm/+lm5v/WVNT/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWbm/+lm5v/WVNT/z87O/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Ozv/pZub/1lTU/+lm5v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/pZub/1lTU/+lm5v/Pzs7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD87O/+lm5v/WVNT/1lTU/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/+lm5v/WVNT/1lTU/8/Ozv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzs7/1lTU/9ZU1P/WVNT/3Jra/9ya2v/Pzs7/3Jra/9ya2v/cmtr/3Jra/+lm5v/cmtr/z87O/+lm5v/cmtr/3Jra/9ya2v/cmtr/z87O/9ya2v/cmtr/1lTU/9ZU1P/WVNT/z87O/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/9ya2v/Pzs7/z87O/9ZU1P/WVNT/3Jra/+lm5v/pZub/6Wbm/9ya2v/Pzs7/6Wbm/+lm5v/cmtr/z87O/9ZU1P/WVNT/z87O/8/Ozv/cmtr/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/cmtr/3Jra/8/Ozv/WVNT/1lTU/9ya2v/cmtr/z87O/+lm5v/pZub/6Wbm/+lm5v/cmtr/3Jra/8/Ozv/Pzs7/6Wbm/9ZU1P/WVNT/z87O/9ya2v/cmtr/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJra/9ya2v/Pzs7/1lTU/9ZU1P/cmtr/6Wbm/8/Ozv/Pzs7/6Wbm/+lm5v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/Pzs7/z87O/9ZU1P/WVNT/z87O/9ya2v/cmtr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/9ya2v/WVNT/1lTU/+lm5v/pZub/6Wbm/9ya2v/pZub/3Jra/9ya2v/Pzs7/3Jra/9ya2v/cmtr/3Jra/9ya2v/Pzs7/1lTU/9ZU1P/cmtr/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/cmtr/3Jra/9ZU1P/cmtr/z87O/+lm5v/cmtr/6Wbm/9ya2v/cmtr/z87O/8/Ozv/cmtr/3Jra/9ya2v/pZub/3Jra/8/Ozv/Pzs7/1lTU/9ya2v/cmtr/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJra/9ya2v/cmtr/1lTU/9ya2v/Pzs7/3Jra/+lm5v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/+lm5v/cmtr/z87O/8/Ozv/WVNT/3Jra/9ya2v/cmtr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/9ya2v/WVNT/6Wbm/+lm5v/pZub/6Wbm/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/Pzs7/6Wbm/9ya2v/Pzs7/z87O/9ZU1P/cmtr/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/cmtr/3Jra/9ZU1P/pZub/6Wbm/+lm5v/cmtr/3Jra/9ya2v/Pzs7/3Jra/9ya2v/cmtr/z87O/8/Ozv/cmtr/z87O/8/Ozv/Pzs7/1lTU/9ya2v/cmtr/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJra/9ya2v/cmtr/1lTU/9ya2v/cmtr/z87O/+lm5v/cmtr/z87O/8/Ozv/cmtr/3Jra/9ya2v/pZub/6Wbm/9ya2v/Pzs7/z87O/8/Ozv/WVNT/3Jra/9ya2v/cmtr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/9ya2v/WVNT/1lTU/8/Ozv/Pzs7/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/6Wbm/+lm5v/cmtr/3Jra/8/Ozv/Pzs7/1lTU/9ZU1P/cmtr/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/cmtr/3Jra/9ZU1P/pZub/1lTU/9ya2v/pZub/3Jra/9ya2v/cmtr/6Wbm/+lm5v/pZub/3Jra/9ya2v/Pzs7/z87O/9ZU1P/Pzs7/1lTU/9ya2v/cmtr/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJra/9ya2v/cmtr/1lTU/+lm5v/WVNT/z87O/9ya2v/cmtr/z87O/+lm5v/pZub/3Jra/9ya2v/Pzs7/z87O/8/Ozv/Pzs7/1lTU/8/Ozv/WVNT/3Jra/9ya2v/cmtr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/9ya2v/WVNT/1lTU/+lm5v/WVNT/z87O/8/Ozv/Pzs7/3Jra/9ya2v/Pzs7/z87O/8/Ozv/Pzs7/z87O/9ZU1P/Pzs7/1lTU/9ZU1P/cmtr/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/cmtr/3Jra/9ZU1P/WVNT/6Wbm/9ya2v/WVNT/1lTU/8/Ozv/Pzs7/z87O/8/Ozv/Pzs7/z87O/9ZU1P/WVNT/z87O/8/Ozv/WVNT/1lTU/9ya2v/cmtr/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJra/9ya2v/cmtr/1lTU/9ZU1P/WVNT/3Jra/+lm5v/cmtr/1lTU/9ZU1P/WVNT/1lTU/9ZU1P/WVNT/z87O/8/Ozv/Pzs7/1lTU/9ZU1P/WVNT/3Jra/9ya2v/cmtr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcmtr/3Jra/8/Ozv/WVNT/1lTU/9ZU1P/WVNT/6Wbm/9ya2v/pZub/3Jra/9ya2v/WVNT/1lTU/8/Ozv/Pzs7/z87O/9ZU1P/WVNT/1lTU/9ZU1P/Pzs7/3Jra/9ya2v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABya2v/pZub/3Jra/8/Ozv/WVNT/1lTU/9ZU1P/WVNT/1lTU/+lm5v/cmtr/3Jra/9ZU1P/WVNT/z87O/9ZU1P/WVNT/1lTU/9ZU1P/WVNT/z87O/9ya2v/pZub/3Jra/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWbm/+lm5v/WVNT/z87O/8/Ozv/WVNT/1lTU/9ZU1P/WVNT/1lTU/9ZU1P/WVNT/1lTU/9ZU1P/WVNT/1lTU/9ZU1P/WVNT/1lTU/8/Ozv/Pzs7/6Wbm/+lm5v/WVNT/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Ozv/pZub/1lTU/+lm5v/cmtr/3Jra/8/Ozv/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/Pzs7/3Jra/9ya2v/pZub/1lTU/+lm5v/Pzs7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD87O/+lm5v/WVNT/1lTU/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/+lm5v/WVNT/1lTU/8/Ozv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzs7/1lTU/9ZU1P/WVNT/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/3Jra/9ya2v/cmtr/1lTU/9ZU1P/WVNT/z87O/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Ozv/Pzs7/z87O/8/Ozv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzs7/z87O/8/Ozv/Pzs7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
    var surf_buffer = surface_create(32, 32);
    buffer_set_surface(buffer_sprite, surf_buffer, 0, 0, 0);    //copy the decoded sprite data onto the surface
    var spr_tower_gun = sprite_create_from_surface(surf_buffer, 0, 0, 32, 32, false, false, 0, 0); //create sprite from this surface
    ds_map_add(0, "spr_tower_gun", spr_tower_gun);
    surface_reset_target();
    surface_free(surf_buffer);
    
    buffer_delete(buffer_sprite);
    
    //== 32px, Draw Method ==
    var surf_spr32 = surface_create(32, 32);
    //black box
    surface_set_target(surf_spr32);
    draw_set_colour(c_gray);
    draw_rectangle(0, 0, 31, 31, false);
    draw_set_colour(c_black);
    draw_rectangle(0, 0, 31, 31, true);
    var spr_box_black = sprite_create_from_surface(surf_spr32, 0, 0, 32, 32, false, false, 0, 0);
    ds_map_add(0, "spr_box_black", spr_box_black);
    
    //grass box
    draw_clear_alpha(c_white, 0);
    draw_set_colour($25C638);
    draw_rectangle(0, 0, 31, 31, false);
    draw_set_colour($2BB23B);
    draw_rectangle(0, 0, 31, 31, true);
    var spr_box_grass = sprite_create_from_surface(surf_spr32, 0, 0, 32, 32, false, false, 0, 0);
    ds_map_add(0, "spr_box_grass", spr_box_grass);
    
    //sand box
    draw_clear_alpha(c_white, 0);
    draw_set_colour($45E0E6);
    draw_rectangle(0, 0, 31, 31, false);
    draw_set_colour($3DC7CC);
    draw_rectangle(0, 0, 31, 31, true);
    var spr_box_sand = sprite_create_from_surface(surf_spr32, 0, 0, 32, 32, false, false, 0, 0);
    ds_map_add(0, "spr_box_sand", spr_box_sand);
    
    draw_set_colour(c_black);
    surface_free(surf_spr32);
    
    
    //===== GENERATE MAP =====
    var surf_map = surface_create(room_width, room_height);
    surface_set_target(surf_map);
    for (var i=0; i<ceil(room_width/32); i++) {
        for (var j=0; j<ceil(room_height/32); j++) {
            draw_sprite(spr_box_grass, 0, i*32, j*32);
        }
    }
    
    //===== GENERATE PATH =====
    var path = path_add();
    ds_map_add(0, "path", path);
    
    var path_dir = 2;
    var path_xtile = 4;
    var path_ytile = 0;
    draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
    path_add_point(path, path_xtile*32, path_ytile*32, 100);
    tile_grid[# path_xtile, path_ytile] = 1;
    repeat(2) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(2) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(5) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(7) {
        path_xtile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(4) {
        path_ytile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(13) {
        path_xtile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(4) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(2) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(5) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(3) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(4) {
        path_ytile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(3) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(6) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(7) {
        path_xtile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(3) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(11) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(5) {
        path_ytile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(6) {
        path_xtile--;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    repeat(6) {
        path_ytile++;
        draw_sprite(spr_box_sand, 0, path_xtile*32, path_ytile*32);
        path_add_point(path, path_xtile*32, path_ytile*32, 100);
        tile_grid[# path_xtile, path_ytile] = 1;
    }
    surface_reset_target();
    
    var spr_map = sprite_create_from_surface(surf_map, 0, 0, room_width, room_height, false, false, 0, 0);
    ds_map_add(0, "spr_map", spr_map);
    
    
    //===== ENEMY DATA =====
    /* use multiple lists to give each enemy a unique id to track their info with */
    var enemy_x = ds_list_create();
    var enemy_y = ds_list_create();
    var enemy_pos = ds_list_create();   //directly related to how many tiles they've crossed
    var enemy_hp = ds_list_create();
    var enemy_maxhp = ds_list_create();
    var enemy_spd = ds_list_create();
    var enemy_dmg = ds_list_create();
    
}


////////// LOCAL VARIABLES //////////
var count = ds_map_find_value(0, "count");
var money = ds_map_find_value(0, "money");
var debug = ds_map_find_value(0, "debug");

var xpos = ds_map_find_value(0, "xpos");
var ypos = ds_map_find_value(0, "ypos");
var xvel = ds_map_find_value(0, "xvel");
var yvel = ds_map_find_value(0, "yvel");

var spr_tower_arrow = ds_map_find_value(0, "spr_tower_arrow");
var spr_tower_gun = ds_map_find_value(0, "spr_tower_gun");

var tile_grid = ds_map_find_value(0, "tile_grid");

var need_money_count = ds_map_find_value(0, "need_money_count");
var menu_count = ds_map_find_value(0, "menu_count");
var menu_open = ds_map_find_value(0, "menu_open");
var menu_tower_held = ds_map_find_value(0, "menu_tower_held");

var tower_id_info = ds_map_find_value(0, "tower_id_info");

var towers = ds_map_find_value(0, "towers");

var rkey = keyboard_check(vk_right) || keyboard_check(ord("D"));
var lkey = keyboard_check(vk_left) || keyboard_check(ord("A"));
var ukey = keyboard_check(vk_up) || keyboard_check(ord("W"));
var dkey = keyboard_check(vk_down) || keyboard_check(ord("S"));


////////// STEP //////////
//== Character ==
if ((rkey && lkey) || !(rkey || lkey)) {
    if (abs(xvel) >= 1) {
        xvel = xvel - sign(xvel);
    } else {
        xvel = 0;
    }
} else {
    if (rkey) xvel += 2;
    if (lkey) xvel += -2;
    if (abs(xvel) > 4) xvel = 4*sign(xvel);
}
if ((ukey && dkey) || !(ukey || dkey)) {
    if (abs(yvel) >= 1) {
        yvel = yvel - sign(yvel);
    } else {
        yvel = 0;
    }
} else {
    if (ukey) yvel += -2;
    if (dkey) yvel += 2;
    if (abs(yvel) > 4) yvel = 4*sign(yvel);
}

//== Map Interaction ==
//cancel tower placement
if (menu_tower_held != -1 && keyboard_check_pressed(vk_escape)) {
    money += towers[# menu_tower_held, 2];
    menu_tower_held = -1;
}

//tower placement
if (menu_tower_held != -1) {
    var place_tilex = mouse_x div 32;
    var place_tiley = mouse_y div 32;
    if (tile_grid[# place_tilex, place_tiley] == 0) {
        //if able to be placed, draw snapped to grid
        var place_x = place_tilex*32;
        var place_y = place_tiley*32;
        var place_able = true;
    } else {
        //if over a blocked location, draw at mouse coords
        var place_x = mouse_x;
        var place_y = mouse_y;
        var place_able = false;
    }
    if (mouse_check_button_released(mb_left) && place_able) {
        //TOWER GRID ID = 10 + grid_position
        //set the specific grid tile to it's unique TOWER GRID ID, so we can reference it for data about the tower
        var tower_id = 10 + place_tilex + (place_tiley*25);
        tile_grid[# place_tilex, place_tiley] = tower_id;
        tower_id_info[# tower_id, 0] = menu_tower_held; //set the tower_type to the one we just placed (0=arrow, 1=gun, ...)
        tower_id_info[# tower_id, 1] = 0;   //set upgr_lvl to 0
        tower_id_info[# tower_id, 2] = 0;   //set att_count to 0
        
        menu_tower_held = -1;
    }
}

//== Menu ==
if ( mouse_y > (room_height-16-(menu_count*6)) ) {
    menu_count++;
    if (menu_count > 10) {
        menu_count = 10;
        menu_open = true;
    } else {
        menu_open = false;
    }
} else {
    menu_count--;
    if (menu_count < 0) {
        menu_count = 0;
    }
}

//menu mouse selection
var menu_y = room_height-10-(menu_count*6);
var menu_sel = -1;
var menu_pressed = false;
var menu_action = false;
if (point_in_rectangle(mouse_x, mouse_y, 3, menu_y, 3+64, menu_y+64)) {
    //we are selecting tower_arrow
    menu_sel = 0;
}
if (point_in_rectangle(mouse_x, mouse_y, 3+64+8, menu_y, 3+64+8+64, menu_y+64)) {
    //we are selecting tower_gun
    menu_sel = 1;
}
if (mouse_check_button(mb_left) && menu_sel != -1) {
    menu_pressed = true;
} else {
    menu_pressed = false;
}
if (mouse_check_button_released(mb_left) && menu_sel != -1) {
    menu_action = true;
} else {
    menu_action = false;
}

//menu tower purchasing
if (menu_action && menu_tower_held == -1) {
    //if we clicked, and aren't already placing a tower, attempt to buy a tower
    if (money >= towers[# menu_sel, 2]) {
        //purchased
        money -= towers[# menu_sel, 2];
        menu_tower_held = menu_sel; //set held tower to the one we selected
        var place_x = mouse_x;
        var place_y = mouse_y;
        var place_able = false;
    } else {
        //not enough money
        need_money_count = 61;
    }
}




////////// END STEP //////////
xpos += xvel;
ypos += yvel;

count += 1;
need_money_count--;
if (need_money_count < -1) need_money_count = -1;


////////// DRAW //////////
//== Draw map ==
var spr_map = ds_map_find_value(0, "spr_map");
draw_sprite(spr_map, 0, 0, 0);

//== Draw character ==
draw_rectangle_colour(xpos+1, ypos+1, xpos+15, ypos+15, c_red, c_yellow, c_blue, c_lime, false);
draw_rectangle(xpos, ypos, xpos+16, ypos+16, true);

//== Draw Towers on Map ==
for (j=0; j<19; j++) {
    for (i=0; i<25; i++) {
        var grid_val = tile_grid[# i, j];
        if (grid_val >= 10) {
            switch (tower_id_info[# grid_val, 0]) {
                case 0: {
                    draw_sprite(spr_tower_arrow, 0, i*32, j*32);
                } break;
                case 1: {
                    draw_sprite(spr_tower_gun, 0, i*32, j*32);
                } break;
            }
        }
    }
}

//== Draw tile highlight below mouse ==
if ( (tile_grid[# (mouse_x div 32), (mouse_y div 32)] != 1) && (mouse_y <= (room_height-16-(menu_count*6))) ) {
    //if we're not hovering over a sand tile, and we're not in the menu
    if (mouse_check_button(mb_left)) {
        draw_set_alpha(0.3);
        draw_set_colour(c_black);
        draw_rectangle((mouse_x div 32)*32, (mouse_y div 32)*32, ((mouse_x+32) div 32)*32-1, ((mouse_y+32) div 32)*32-1, false);
        draw_set_alpha(1);
    } else {
        draw_set_alpha(0.3);
        draw_set_colour(c_white);
        draw_rectangle((mouse_x div 32)*32, (mouse_y div 32)*32, ((mouse_x+32) div 32)*32-1, ((mouse_y+32) div 32)*32-1, false);
        draw_set_alpha(1);
        draw_set_colour(c_black);
    }
}

//== Draw "Not Enough Money" Text
if (need_money_count > -1) {
    draw_set_halign(fa_center);
    draw_set_valign(fa_middle);
    draw_set_colour($3A3AFF);
    draw_text_transformed_colour(room_width/2, room_height/2, "Not Enough Money", 4+(0.5*sin(count/20)), 4+(0.5*sin(count/20)), 0, $3A3AFF, $3A3AFF, $3A3AFF, $3A3AFF, (need_money_count*1.5)/60 );
    draw_set_halign(fa_left);
    draw_set_valign(fa_top);
    draw_set_colour(c_black);
}

//===== DRAW MENU =====
draw_set_alpha(0.5);
draw_rectangle(0, room_height-16-(menu_count*6), room_width, room_height, false);
draw_set_alpha(0.35);

//== Tower icon bg ==
draw_roundrect(3, menu_y, 3+64, menu_y+64, false);
draw_roundrect(3+64+8, menu_y, 3+64+8+64, menu_y+64, false);
draw_set_alpha(1);

//== Tower icons ==
draw_sprite_stretched(spr_tower_arrow, 0, 4, menu_y+2, 64, 64);
draw_sprite_stretched(spr_tower_gun, 0, 4+64+8, menu_y+2, 64, 64);
if (menu_pressed) {
    //mouse down on the icon
    switch (menu_sel) {
        case 0: {
            d3d_set_fog(true, c_black, 0, 0);
            draw_set_alpha(0.2);
            draw_sprite_stretched(spr_tower_arrow, 0, 4, menu_y+2, 64, 64);
            d3d_set_fog(false, c_black, 0, 0);
            draw_set_alpha(1);
        } break;
        case 1: {
            d3d_set_fog(true, c_black, 0, 0);
            draw_set_alpha(0.2);
            draw_sprite_stretched(spr_tower_gun, 0, 4+64+8, menu_y+2, 64, 64);
            d3d_set_fog(false, c_black, 0, 0);
            draw_set_alpha(1);
        } break;
    }
} else {
    //we are hovering over the icon
    switch (menu_sel) {
        case 0: {
            d3d_set_fog(true, c_white, 0, 0);
            draw_set_alpha(0.25);
            draw_sprite_stretched(spr_tower_arrow, 0, 4, menu_y+2, 64, 64);
            d3d_set_fog(false, c_white, 0, 0);
            draw_set_alpha(1);
        } break;
        case 1: {
            d3d_set_fog(true, c_white, 0, 0);
            draw_set_alpha(0.25);
            draw_sprite_stretched(spr_tower_gun, 0, 4+64+8, menu_y+2, 64, 64);
            d3d_set_fog(false, c_white, 0, 0);
            draw_set_alpha(1);
        } break;
    }
}

//== Tower information ==
if (menu_sel != -1) {
    draw_set_alpha(0.35);
    draw_rectangle(100, room_height-16-(menu_count*6)-90, room_width-100, room_height-16-(menu_count*6)-1, false);
    draw_set_alpha(0.25);
    draw_rectangle(100, room_height-16-(menu_count*6)-90, room_width-100, room_height-16-(menu_count*6)-1, true);
    draw_set_halign(fa_center);
    draw_set_alpha(1);
    draw_set_colour(c_black);
    
    //selected tower details
    var name = towers[# menu_sel, 0];
    var desc = towers[# menu_sel, 1];
    var cost = towers[# menu_sel, 2];
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-88+3, name, 3, 3, 0);
    draw_set_colour(c_white);
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-88, name, 3, 3, 0);
    draw_set_colour(c_black);
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-50+2, desc, 2, 2, 0);
    draw_set_colour($BBBBBB);
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-50, desc, 2, 2, 0);
    draw_set_colour(c_black);
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-21+2, "Cost: "+string(cost), 2, 2, 0);
    draw_set_colour(c_white);
    draw_text_transformed(room_width/2, room_height-16-(menu_count*6)-21, "Cost: "+string(cost), 2, 2, 0);
    draw_set_colour(c_black);
            
    draw_set_halign(fa_left);
}

//== Tower placement ==
if (menu_tower_held != -1) {
    window_set_cursor(cr_cross);
    switch (menu_tower_held) {
        case 0: {
            draw_sprite_ext(spr_tower_arrow, 0, place_x, place_y, 1.25+(0.25*cos((count-30)/20)), 1.25+(0.25*cos((count-30)/20)), 0, -1, 1);
        } break;
        case 1: {
            draw_sprite_ext(spr_tower_gun, 0, place_x, place_y, 1.25+(0.25*cos((count-30)/20)), 1.25+(0.25*cos((count-30)/20)), 0, -1, 1);
        } break;
    }
    draw_set_alpha(0.5);
    draw_text_transformed(mouse_x, mouse_y-10, "Press 'ESC' to cancel placement and get a refund", 2, 2, 0);
    draw_set_alpha(1);
} else {
    window_set_cursor(cr_default);
}

//== Draw Current Money (outlined) ==
draw_set_colour(c_black);
draw_text_transformed(0, 0, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(0, 2, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(0, 4, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(2, 4, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(4, 4, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(4, 2, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(4, 0, "Money: " + string(money), 2, 2, 0);
draw_text_transformed(2, 0, "Money: " + string(money), 2, 2, 0);
draw_set_colour($2D93FF);
draw_text_transformed(2, 2, "Money: " + string(money), 2, 2, 0);
draw_set_colour(c_black);


////////// DEBUG //////////
if (keyboard_check_pressed(vk_control)) {
    debug = !debug;
}
if (debug) { 
    show_debug_overlay(true);
    
    //draw vars
    draw_text_transformed(0, 12,
    "count: " + string(count) +"#"+
    //"money: " + string(money) +"#"+
    ""
    , 2, 2, 0);
    
    //draw map grid values
    for (j=0; j<19; j++) {
        for (i=0; i<25; i++) {
            if (tile_grid[# i, j] >= 10) {
                draw_text((i*32)+2, (j*32)+2, string( tile_grid[# i, j] ));
            }
        }
    }
    
}


////////// UPDATE DS_MAP //////////
ds_map_replace(0, "count", count);
ds_map_replace(0, "money", money);
ds_map_replace(0, "debug", debug);

ds_map_replace(0, "menu_count", menu_count);
ds_map_replace(0, "menu_open", menu_open);
ds_map_replace(0, "menu_tower_held", menu_tower_held);
ds_map_replace(0, "need_money_count", need_money_count);

ds_map_replace(0, "xpos", xpos);
ds_map_replace(0, "ypos", ypos);
ds_map_replace(0, "xvel", xvel);
ds_map_replace(0, "yvel", yvel);
