//feather ignore all
#region TokenType
#macro __GMLC_TokenType_Whitespace 0
#macro __GMLC_TokenType_Identifier 1
#macro __GMLC_TokenType_Number 2
#macro __GMLC_TokenType_Operator 3
#macro __GMLC_TokenType_Keyword 4
#macro __GMLC_TokenType_Function 5
#macro __GMLC_TokenType_Punctuation 6
#macro __GMLC_TokenType_UniqueVariable 7
#macro __GMLC_TokenType_String 8
#macro __GMLC_TokenType_TemplateStringBegin 9
#macro __GMLC_TokenType_TemplateStringMiddle 10
#macro __GMLC_TokenType_TemplateStringEnd 11
#macro __GMLC_TokenType_EscapeOperator 12
#macro __GMLC_TokenType_Comment 13
#macro __GMLC_TokenType_Macro 14
#macro __GMLC_TokenType_Region 15
#macro __GMLC_TokenType_Enum 16
#macro __GMLC_TokenType_Define 17
#macro __GMLC_TokenType_NoOpPragma 18
#macro __GMLC_TokenType_Illegal 19
#macro __GMLC_TokenType_SIZE 20
#macro Debug:__GMLC_TokenType_Whitespace "__GMLC_TokenType_Whitespace"
#macro Debug:__GMLC_TokenType_Identifier "__GMLC_TokenType_Identifier"
#macro Debug:__GMLC_TokenType_Number "__GMLC_TokenType_Number"
#macro Debug:__GMLC_TokenType_Operator "__GMLC_TokenType_Operator"
#macro Debug:__GMLC_TokenType_Keyword "__GMLC_TokenType_Keyword"
#macro Debug:__GMLC_TokenType_Function "__GMLC_TokenType_Function"
#macro Debug:__GMLC_TokenType_Punctuation "__GMLC_TokenType_Punctuation"
#macro Debug:__GMLC_TokenType_UniqueVariable "__GMLC_TokenType_UniqueVariable"
#macro Debug:__GMLC_TokenType_String "__GMLC_TokenType_String"
#macro Debug:__GMLC_TokenType_TemplateStringBegin "__GMLC_TokenType_TemplateStringBegin"
#macro Debug:__GMLC_TokenType_TemplateStringMiddle "__GMLC_TokenType_TemplateStringMiddle"
#macro Debug:__GMLC_TokenType_TemplateStringEnd "__GMLC_TokenType_TemplateStringEnd"
#macro Debug:__GMLC_TokenType_EscapeOperator "__GMLC_TokenType_EscapeOperator"
#macro Debug:__GMLC_TokenType_Comment "__GMLC_TokenType_Comment"
#macro Debug:__GMLC_TokenType_Macro "__GMLC_TokenType_Macro"
#macro Debug:__GMLC_TokenType_Region "__GMLC_TokenType_Region"
#macro Debug:__GMLC_TokenType_Enum "__GMLC_TokenType_Enum"
#macro Debug:__GMLC_TokenType_Define "__GMLC_TokenType_Define"
#macro Debug:__GMLC_TokenType_NoOpPragma "__GMLC_TokenType_NoOpPragma"
#macro Debug:__GMLC_TokenType_Illegal "__GMLC_TokenType_Illegal"
#endregion
#region NodeKind
#macro __GMLC_NodeKind_Script 0
#macro __GMLC_NodeKind_Block 1
#macro __GMLC_NodeKind_FunctionDecl 2
#macro __GMLC_NodeKind_ConstructorDecl 3
#macro __GMLC_NodeKind_Param 4
#macro __GMLC_NodeKind_StaticDecl 5
#macro __GMLC_NodeKind_VarDecl 6
#macro __GMLC_NodeKind_VarDeclList 7
#macro __GMLC_NodeKind_GlobalVarDecl 8
#macro __GMLC_NodeKind_EnumDecl 9
#macro __GMLC_NodeKind_EnumMember 10
#macro __GMLC_NodeKind_MacroDecl 11
#macro __GMLC_NodeKind_If 12
#macro __GMLC_NodeKind_For 13
#macro __GMLC_NodeKind_While 14
#macro __GMLC_NodeKind_Repeat 15
#macro __GMLC_NodeKind_DoUntil 16
#macro __GMLC_NodeKind_With 17
#macro __GMLC_NodeKind_Switch 18
#macro __GMLC_NodeKind_Case 19
#macro __GMLC_NodeKind_Default 20
#macro __GMLC_NodeKind_Try 21
#macro __GMLC_NodeKind_Break 22
#macro __GMLC_NodeKind_Continue 23
#macro __GMLC_NodeKind_Exit 24
#macro __GMLC_NodeKind_Return 25
#macro __GMLC_NodeKind_Throw 26
#macro __GMLC_NodeKind_Delete 27
#macro __GMLC_NodeKind_ExprStmt 28
#macro __GMLC_NodeKind_Assign 29
#macro __GMLC_NodeKind_Binary 30
#macro __GMLC_NodeKind_Logical 31
#macro __GMLC_NodeKind_Nullish 32
#macro __GMLC_NodeKind_Unary 33
#macro __GMLC_NodeKind_Update 34
#macro __GMLC_NodeKind_Conditional 35
#macro __GMLC_NodeKind_Call 36
#macro __GMLC_NodeKind_MethodCall 37
#macro __GMLC_NodeKind_New 38
#macro __GMLC_NodeKind_Index 39
#macro __GMLC_NodeKind_Identifier 40
#macro __GMLC_NodeKind_Literal 41
#macro __GMLC_NodeKind_ArrayLiteral 42
#macro __GMLC_NodeKind_StructLiteral 43
#macro __GMLC_NodeKind_StructEntry 44
#macro __GMLC_NodeKind_TemplateString 45
#macro __GMLC_NodeKind_FunctionExpr 46
#macro __GMLC_NodeKind_Nameof 47
#macro __GMLC_NodeKind_Empty 48
#macro __GMLC_NodeKind_SIZE 49
#macro Debug:__GMLC_NodeKind_Script "__GMLC_NodeKind_Script"
#macro Debug:__GMLC_NodeKind_Block "__GMLC_NodeKind_Block"
#macro Debug:__GMLC_NodeKind_FunctionDecl "__GMLC_NodeKind_FunctionDecl"
#macro Debug:__GMLC_NodeKind_ConstructorDecl "__GMLC_NodeKind_ConstructorDecl"
#macro Debug:__GMLC_NodeKind_Param "__GMLC_NodeKind_Param"
#macro Debug:__GMLC_NodeKind_StaticDecl "__GMLC_NodeKind_StaticDecl"
#macro Debug:__GMLC_NodeKind_VarDecl "__GMLC_NodeKind_VarDecl"
#macro Debug:__GMLC_NodeKind_VarDeclList "__GMLC_NodeKind_VarDeclList"
#macro Debug:__GMLC_NodeKind_GlobalVarDecl "__GMLC_NodeKind_GlobalVarDecl"
#macro Debug:__GMLC_NodeKind_EnumDecl "__GMLC_NodeKind_EnumDecl"
#macro Debug:__GMLC_NodeKind_EnumMember "__GMLC_NodeKind_EnumMember"
#macro Debug:__GMLC_NodeKind_MacroDecl "__GMLC_NodeKind_MacroDecl"
#macro Debug:__GMLC_NodeKind_If "__GMLC_NodeKind_If"
#macro Debug:__GMLC_NodeKind_For "__GMLC_NodeKind_For"
#macro Debug:__GMLC_NodeKind_While "__GMLC_NodeKind_While"
#macro Debug:__GMLC_NodeKind_Repeat "__GMLC_NodeKind_Repeat"
#macro Debug:__GMLC_NodeKind_DoUntil "__GMLC_NodeKind_DoUntil"
#macro Debug:__GMLC_NodeKind_With "__GMLC_NodeKind_With"
#macro Debug:__GMLC_NodeKind_Switch "__GMLC_NodeKind_Switch"
#macro Debug:__GMLC_NodeKind_Case "__GMLC_NodeKind_Case"
#macro Debug:__GMLC_NodeKind_Default "__GMLC_NodeKind_Default"
#macro Debug:__GMLC_NodeKind_Try "__GMLC_NodeKind_Try"
#macro Debug:__GMLC_NodeKind_Break "__GMLC_NodeKind_Break"
#macro Debug:__GMLC_NodeKind_Continue "__GMLC_NodeKind_Continue"
#macro Debug:__GMLC_NodeKind_Exit "__GMLC_NodeKind_Exit"
#macro Debug:__GMLC_NodeKind_Return "__GMLC_NodeKind_Return"
#macro Debug:__GMLC_NodeKind_Throw "__GMLC_NodeKind_Throw"
#macro Debug:__GMLC_NodeKind_Delete "__GMLC_NodeKind_Delete"
#macro Debug:__GMLC_NodeKind_ExprStmt "__GMLC_NodeKind_ExprStmt"
#macro Debug:__GMLC_NodeKind_Assign "__GMLC_NodeKind_Assign"
#macro Debug:__GMLC_NodeKind_Binary "__GMLC_NodeKind_Binary"
#macro Debug:__GMLC_NodeKind_Logical "__GMLC_NodeKind_Logical"
#macro Debug:__GMLC_NodeKind_Nullish "__GMLC_NodeKind_Nullish"
#macro Debug:__GMLC_NodeKind_Unary "__GMLC_NodeKind_Unary"
#macro Debug:__GMLC_NodeKind_Update "__GMLC_NodeKind_Update"
#macro Debug:__GMLC_NodeKind_Conditional "__GMLC_NodeKind_Conditional"
#macro Debug:__GMLC_NodeKind_Call "__GMLC_NodeKind_Call"
#macro Debug:__GMLC_NodeKind_MethodCall "__GMLC_NodeKind_MethodCall"
#macro Debug:__GMLC_NodeKind_New "__GMLC_NodeKind_New"
#macro Debug:__GMLC_NodeKind_Index "__GMLC_NodeKind_Index"
#macro Debug:__GMLC_NodeKind_Identifier "__GMLC_NodeKind_Identifier"
#macro Debug:__GMLC_NodeKind_Literal "__GMLC_NodeKind_Literal"
#macro Debug:__GMLC_NodeKind_ArrayLiteral "__GMLC_NodeKind_ArrayLiteral"
#macro Debug:__GMLC_NodeKind_StructLiteral "__GMLC_NodeKind_StructLiteral"
#macro Debug:__GMLC_NodeKind_StructEntry "__GMLC_NodeKind_StructEntry"
#macro Debug:__GMLC_NodeKind_TemplateString "__GMLC_NodeKind_TemplateString"
#macro Debug:__GMLC_NodeKind_FunctionExpr "__GMLC_NodeKind_FunctionExpr"
#macro Debug:__GMLC_NodeKind_Nameof "__GMLC_NodeKind_Nameof"
#macro Debug:__GMLC_NodeKind_Empty "__GMLC_NodeKind_Empty"
#endregion
